### PR TITLE
docusaurus

### PR DESCRIPTION
**Pull request by kylegrover**
initialized docusaurus & copied.wiki.git markdown contents. 

it could use some polish

### CODE REVIEW

**Comment by kylegrover** [comment]
image_1068

**Comment by floydwilde** [comment]
I have migrated the Docusaurus configuration files from this branch and set up a "staging" Docusaurus site using Gitlab Pages here: 

* https://teia-community.gitlab.io/teia-staging-docusaurus/

The wiki files, that were imported into this branch, are now out of date.  This PR is not really going anywhere, the staging work is now happening in the Gitlab repo here: 

* https://gitlab.com/teia-community/teia-staging-docusaurus

We will shortly be doing more configuration of the sidebar and main page there.   

So I don't recommend merging this branch, and at some point we will close it.  Just want to hang on the branch for now for reference and make sure I didn't miss copying anything over.  

I will set this PR to draft status.

**Comment by floydwilde** [comment]
I have created some experimental branches which change the directory structure to better accommodate auto-generating sidebars for Docusarus: 

```
 $ git branch -l -r
  origin/HEAD -> origin/master
  origin/docusarus-autogenerate-directory-sidebar
  origin/docusarus-autogenerated-trial
  origin/master
```
But without a concerted effort to decide on a structure, make those changes and merge them in to master, it will be difficult to track changes on the test git hub site.  The latest branch where I have done this is `docusarus-autogenerate-directory-sidebar` but no longer makes sense to maintain.  You can get an idea what the Docusaurus website gives your here: 

* https://teia-community.gitlab.io/teia-staging-docusaurus/

I didn't quite finish updating the sidebar code to include all the pages.  You can review the code here: 

* https://gitlab.com/teia-community/teia-staging-docusaurus/-/blob/main/website/sidebars.js

And get an idea what needs to be done.  For instance you could create a "charities" or "fundraising" folder to include all the pages for those initiatives and then add code like: 

```
      type: 'category',
      label: 'Fundraisers',
     {
          type: 'autogenerated',
          dirName: 'fundraisers', // Drop Fundraising pages here
        },
      ],
    },
```
Or something like that. 

The Gitlab wiki feature is not very helpful since it hides all the branches and doesn't allow you to create PR's, though there are some various hacky ways around that. 

Anyhow, there is more to Docusaurus than simply installing and throwing your wiki pages at it.  Once you decide on a directory structure that would work with it, there is probably some way to automate the page rebuilds within Github with a post commit hook or an action or some such thing. 

The Gitlab repo is there for staging, since you will want to keep Docusaurus updated and be able to test out new features and things.  V3 is not far away.  

I'll not have much time to work on this anymore, heading off on to another project but reach out to Merchant or myself if you need access to the Gitlab repo.

**Comment by melMass** [comment]
> The Gitlab wiki feature is not very helpful since it hides all the branches and doesn't allow you to create PR's

Same on GitHub unfortunately, but I believe there should be a way to do what we want with some actions for instance this one:

https://github.com/marketplace/actions/bi-directional-wiki-sync-action

I personally will have time by the end of next week to look into all that!

Thanks a lot for the contribution

**Comment by floydwilde** [comment]
I realise now I made a typo, I meant to say the **GitHub** wiki feature is not very helpful since it hides all the branches and doesn't allow you to create PRs.  I don't know if the _GitLab_ wiki is any better, I haven't looked at how it stores files and not really considering that as an option.  I'm just using GitLab for experimenting w/ Docusaurus. 

I was just reading this article: 

* https://nimblehq.co/blog/create-github-wiki-pull-request

Which suggests a one-way sync, putting your GitHub wiki files in a /docs folder and then using a GitHub action along with rsync to keep them in sync.  More of a one way type of sync, but the bidirectional sync @melMass suggests seems like it would also be a suitable option.  

I'm inclined to create an issue that explains this better, and I would encourage us to close this PR and open an issue to discuss using Docusaurus further.  I think getting the wiki files in a more visible place is a good first step, since they need to be massaged a bit before being ready for use with Docusaurus.

**Comment by floydwilde** [comment]
I'm disinclined to use the NewRelic wiki sync action since it seems unmaintained, there are a few outstanding issues and PRs, and they have removed it from their work flow: 

* https://github.com/newrelic/opensource-website/commit/30ee210d1205558adbb5f0424bee162e4f967bda

Still might be useful, but worth looking at other options.

**Comment by floydwilde** [comment]
Closing this PR as it's passed some use by date.  Need to restart the what other Documentation tools to use conversation elsewhere, and we have a place in discord to talk about this now: 

* https://discord.com/channels/908672304236625970/910285126922039338

**Pull request closed without merging**
